language: java

jobs:
   include:
      - stage: CodeQuality
        script: ./gradlew sonarcube

addons:
  sonarcloud:
    organization: $SONAR_USER
    token:
      secure: $SONAR_TOKEN
  
jdk:
  - openjdk11
